Repository vuejs-translations/docs-uk, pull requests merged in 2022-08, with the labels that each got.

#24 Виправлено README.md
  README.md
Labels: invalid

#28 Add files via upload
  src/guide/essentials/images/lifecycle.png
Labels: documentation, invalid

#34 Sync with upstream
  src/about/releases.md
  src/guide/extras/reactivity-in-depth.md
  src/guide/scaling-up/routing.md
  src/partners/activelogic.md
  src/partners/components/PartnerList.vue
  src/partners/partners.json
  src/public/images/partners/activelogic-hero.jpg
  src/public/images/partners/activelogic.png
  src/tutorial/src/step-9/description.md
Labels: синхронізація

#37 Синзронізація з upstream
  src/about/faq.md
  src/about/team/members-partner.json
  src/api/component-instance.md
  src/api/options-state.md
  src/api/reactivity-core.md
  src/guide/best-practices/performance.md
  src/guide/extras/composition-api-faq.md
  src/guide/extras/reactivity-in-depth.md
  src/guide/scaling-up/testing.md
  src/partners/partners.json
Labels: синхронізація

#35 Update routing.md
  src/guide/essentials/component-basics.md
  src/guide/scaling-up/routing.md
Labels: новий переклад

#16 docs: Рендеринг списків
  .vitepress/config.ts
  .vitepress/public/glossary.json
  src/guide/essentials/list.md
  src/public/_redirects
  src/public/glossary.json
Labels: новий переклад
