Repository vuejs-translations/docs-uk, pull requests merged in 2022-10, with the labels that each got.

#67 Sync
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  src/guide/best-practices/performance.md
  src/guide/scaling-up/tooling.md
  src/guide/typescript/overview.md
  src/partners/components/PartnerCard.vue
  src/partners/components/type.ts
  src/partners/components/utils.ts
  src/partners/dreamonkey.md
  src/partners/partners.json
  src/public/images/partners/dreamonkey-hero.png
  src/public/images/partners/dreamonkey.png
  src/public/images/vueschool/bg-desktop.svg
  src/public/images/vueschool/bg-mobile.png
  src/public/images/vueschool/bg-tablet.svg
  src/public/images/vueschool/close.svg
  src/public/images/vueschool/vs-iso.svg
  src/public/images/vueschool/vs-logo.svg
Labels: синхронізація

#69 Update description.txt
  src/examples/src/hello-world/App/composition.js
  src/examples/src/hello-world/App/options.js
  src/examples/src/hello-world/description.txt
Labels: новий переклад

#68 update translation page: add link to source, add Ukrainian wip entry
  src/translations/index.md
Labels: виправлення

#70 Translation for /guide/components/registration.md
  src/guide/components/registration.md
Labels: новий переклад

#78 Sync 1
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  src/api/application.md
  src/api/composition-api-dependency-injection.md
  src/api/composition-api-lifecycle.md
  src/api/options-composition.md
  src/api/options-lifecycle.md
  src/guide/built-ins/keep-alive.md
  src/guide/built-ins/transition.md
  src/guide/components/provide-inject.md
  src/guide/extras/rendering-mechanism.md
  src/tutorial/TutorialRepl.vue
Labels: синхронізація

#79 Український банер
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
Labels: vitepress

#90 Синхронізація з upstream
  src/api/utility-types.md
  src/guide/scaling-up/testing.md
Labels: синхронізація

#103 feat: #93 Форми
  .vitepress/config.ts
  src/guide/essentials/forms.md
Labels: новий переклад

#100 Переклад сторінки template-syntax.md.
  src/guide/essentials/images/directive.png
  src/guide/essentials/template-syntax.md
Labels: новий переклад

#120 Перекладено незначні елементи інтерфейсу
  .vitepress/config.ts
Labels: виправлення, @vue/theme, vitepress

#121 Виправлено "додаток" на "застосунок"
  src/public/glossary.json
Labels: похибка
